DB_DIRECTORY_PATH = "$HOME/.local/state/wiktionary-cli/"
DB_FILE_NAME = "data.db"

DB_SAVE_SEARCHES = True

DB_SAVE_PAGES = True
DB_USE_SAVED_PAGES = True 
DB_PAGE_EXPIRATION_TIME = "10d"

# not yet used:
DB_SAVE_FAILED_SEARCHES = False
DB_PAGE_ARCHIVE_LENGTH = 100
DB_SEARCH_ARCHIVE_LENGTH = 100